package chehui.maichetong.useroperationservice;

import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;
import org.jinouts.xml.ws.RequestWrapper;
import org.jinouts.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-07-07T22:03:19.052+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://UserOperationService.maichetong.chehui/", name = "UserOperationServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface UserOperationServiceSoap {

    @WebMethod(operationName = "GetBrandABC", action = "http://UserOperationService.maichetong.chehui/GetBrandABC")
    @RequestWrapper(localName = "GetBrandABC", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandABC")
    @ResponseWrapper(localName = "GetBrandABCResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandABCResponse")
    @WebResult(name = "GetBrandABCResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBrand getBrandABC();

    @WebMethod(operationName = "OrderQueteBy", action = "http://UserOperationService.maichetong.chehui/OrderQueteBy")
    @RequestWrapper(localName = "OrderQueteBy", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.OrderQueteBy")
    @ResponseWrapper(localName = "OrderQueteByResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.OrderQueteByResponse")
    @WebResult(name = "OrderQueteByResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTQuote orderQueteBy(
        @WebParam(name = "fieldname", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String fieldname
    );

    @WebMethod(operationName = "GetSeriesByMakeName", action = "http://UserOperationService.maichetong.chehui/GetSeriesByMakeName")
    @RequestWrapper(localName = "GetSeriesByMakeName", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByMakeName")
    @ResponseWrapper(localName = "GetSeriesByMakeNameResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByMakeNameResponse")
    @WebResult(name = "GetSeriesByMakeNameResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getSeriesByMakeName(
        @WebParam(name = "brandName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandName
    );

    @WebMethod(operationName = "GetallQueteByUser", action = "http://UserOperationService.maichetong.chehui/GetallQueteByUser")
    @RequestWrapper(localName = "GetallQueteByUser", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetallQueteByUser")
    @ResponseWrapper(localName = "GetallQueteByUserResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetallQueteByUserResponse")
    @WebResult(name = "GetallQueteByUserResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTQuote getallQueteByUser(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetCarColorByCarID", action = "http://UserOperationService.maichetong.chehui/GetCarColorByCarID")
    @RequestWrapper(localName = "GetCarColorByCarID", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarColorByCarID")
    @ResponseWrapper(localName = "GetCarColorByCarIDResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarColorByCarIDResponse")
    @WebResult(name = "GetCarColorByCarIDResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getCarColorByCarID(
        @WebParam(name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetQueteByCarID", action = "http://UserOperationService.maichetong.chehui/GetQueteByCarID")
    @RequestWrapper(localName = "GetQueteByCarID", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetQueteByCarID")
    @ResponseWrapper(localName = "GetQueteByCarIDResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetQueteByCarIDResponse")
    @WebResult(name = "GetQueteByCarIDResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTQuote getQueteByCarID(
        @WebParam(name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetSeriesByCar", action = "http://UserOperationService.maichetong.chehui/GetSeriesByCar")
    @RequestWrapper(localName = "GetSeriesByCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByCar")
    @ResponseWrapper(localName = "GetSeriesByCarResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByCarResponse")
    @WebResult(name = "GetSeriesByCarResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getSeriesByCar(
        @WebParam(name = "brandName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandName,
        @WebParam(name = "makeName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String makeName
    );

    @WebMethod(operationName = "GetUserTel", action = "http://UserOperationService.maichetong.chehui/GetUserTel")
    @RequestWrapper(localName = "GetUserTel", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetUserTel")
    @ResponseWrapper(localName = "GetUserTelResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetUserTelResponse")
    @WebResult(name = "GetUserTelResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTUSER getUserTel(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetSeriesById", action = "http://UserOperationService.maichetong.chehui/GetSeriesById")
    @RequestWrapper(localName = "GetSeriesById", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesById")
    @ResponseWrapper(localName = "GetSeriesByIdResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByIdResponse")
    @WebResult(name = "GetSeriesByIdResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getSeriesById(
        @WebParam(name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetALLBrandName", action = "http://UserOperationService.maichetong.chehui/GetALLBrandName")
    @RequestWrapper(localName = "GetALLBrandName", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetALLBrandName")
    @ResponseWrapper(localName = "GetALLBrandNameResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetALLBrandNameResponse")
    @WebResult(name = "GetALLBrandNameResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBrand getALLBrandName();

    @WebMethod(operationName = "GetSeriesByBrandid_Car", action = "http://UserOperationService.maichetong.chehui/GetSeriesByBrandid_Car")
    @RequestWrapper(localName = "GetSeriesByBrandid_Car", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByBrandidCar")
    @ResponseWrapper(localName = "GetSeriesByBrandid_CarResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByBrandidCarResponse")
    @WebResult(name = "GetSeriesByBrandid_CarResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTCar getSeriesByBrandidCar(
        @WebParam(name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid,
        @WebParam(name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetOrderCarName", action = "http://UserOperationService.maichetong.chehui/GetOrderCarName")
    @RequestWrapper(localName = "GetOrderCarName", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetOrderCarName")
    @ResponseWrapper(localName = "GetOrderCarNameResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetOrderCarNameResponse")
    @WebResult(name = "GetOrderCarNameResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTCar getOrderCarName(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetSeriesBybrandsCar", action = "http://UserOperationService.maichetong.chehui/GetSeriesBybrandsCar")
    @RequestWrapper(localName = "GetSeriesBybrandsCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesBybrandsCar")
    @ResponseWrapper(localName = "GetSeriesBybrandsCarResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesBybrandsCarResponse")
    @WebResult(name = "GetSeriesBybrandsCarResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTCar getSeriesBybrandsCar(
        @WebParam(name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid,
        @WebParam(name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid,
        @WebParam(name = "seriescar", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriescar
    );

    @WebMethod(operationName = "GetBrandName", action = "http://UserOperationService.maichetong.chehui/GetBrandName")
    @RequestWrapper(localName = "GetBrandName", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandName")
    @ResponseWrapper(localName = "GetBrandNameResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandNameResponse")
    @WebResult(name = "GetBrandNameResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBrand getBrandName(
        @WebParam(name = "BrandABC", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandABC
    );

    @WebMethod(operationName = "GetBrandNameByBrandNameEn", action = "http://UserOperationService.maichetong.chehui/GetBrandNameByBrandNameEn")
    @RequestWrapper(localName = "GetBrandNameByBrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandNameByBrandNameEn")
    @ResponseWrapper(localName = "GetBrandNameByBrandNameEnResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandNameByBrandNameEnResponse")
    @WebResult(name = "GetBrandNameByBrandNameEnResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBrand getBrandNameByBrandNameEn(
        @WebParam(name = "BrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandNameEn
    );

    @WebMethod(operationName = "GetMakeNames", action = "http://UserOperationService.maichetong.chehui/GetMakeNames")
    @RequestWrapper(localName = "GetMakeNames", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMakeNames")
    @ResponseWrapper(localName = "GetMakeNamesResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMakeNamesResponse")
    @WebResult(name = "GetMakeNamesResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getMakeNames(
        @WebParam(name = "makename", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String makename
    );

    @WebMethod(operationName = "GetCarByseriesId", action = "http://UserOperationService.maichetong.chehui/GetCarByseriesId")
    @RequestWrapper(localName = "GetCarByseriesId", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByseriesId")
    @ResponseWrapper(localName = "GetCarByseriesIdResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByseriesIdResponse")
    @WebResult(name = "GetCarByseriesIdResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTCar getCarByseriesId(
        @WebParam(name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetSeriesName", action = "http://UserOperationService.maichetong.chehui/GetSeriesName")
    @RequestWrapper(localName = "GetSeriesName", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesName")
    @ResponseWrapper(localName = "GetSeriesNameResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesNameResponse")
    @WebResult(name = "GetSeriesNameResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getSeriesName();

    @WebMethod(operationName = "GetMyOrderDetails", action = "http://UserOperationService.maichetong.chehui/GetMyOrderDetails")
    @RequestWrapper(localName = "GetMyOrderDetails", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMyOrderDetails")
    @ResponseWrapper(localName = "GetMyOrderDetailsResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMyOrderDetailsResponse")
    @WebResult(name = "GetMyOrderDetailsResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTOrder getMyOrderDetails(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid,
        @WebParam(name = "carId", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carId
    );

    @WebMethod(operationName = "GetSeriesByBrandid", action = "http://UserOperationService.maichetong.chehui/GetSeriesByBrandid")
    @RequestWrapper(localName = "GetSeriesByBrandid", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByBrandid")
    @ResponseWrapper(localName = "GetSeriesByBrandidResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetSeriesByBrandidResponse")
    @WebResult(name = "GetSeriesByBrandidResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getSeriesByBrandid(
        @WebParam(name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid
    );

    @WebMethod(operationName = "GetCarByBrandId", action = "http://UserOperationService.maichetong.chehui/GetCarByBrandId")
    @RequestWrapper(localName = "GetCarByBrandId", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByBrandId")
    @ResponseWrapper(localName = "GetCarByBrandIdResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByBrandIdResponse")
    @WebResult(name = "GetCarByBrandIdResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getCarByBrandId(
        @WebParam(name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid
    );

    @WebMethod(operationName = "AddOrder", action = "http://UserOperationService.maichetong.chehui/AddOrder")
    @RequestWrapper(localName = "AddOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.AddOrder")
    @ResponseWrapper(localName = "AddOrderResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.AddOrderResponse")
    @WebResult(name = "AddOrderResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfTOrder addOrder(
        @WebParam(name = "userID", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        int userID,
        @WebParam(name = "carID", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        int carID,
        @WebParam(name = "cityname", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String cityname,
        @WebParam(name = "ExpectPrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String expectPrice,
        @WebParam(name = "InsurancePrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String insurancePrice,
        @WebParam(name = "LicensePrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String licensePrice,
        @WebParam(name = "Description", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String description,
        @WebParam(name = "carColor", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carColor,
        @WebParam(name = "CarPlan", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carPlan,
        @WebParam(name = "PayMode", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String payMode,
        @WebParam(name = "CarAddress", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carAddress,
        @WebParam(name = "ZhuangHuang", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String zhuangHuang,
        @WebParam(name = "kehuqw", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String kehuqw
    );

    @WebMethod(operationName = "GetMyOrder", action = "http://UserOperationService.maichetong.chehui/GetMyOrder")
    @RequestWrapper(localName = "GetMyOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMyOrder")
    @ResponseWrapper(localName = "GetMyOrderResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetMyOrderResponse")
    @WebResult(name = "GetMyOrderResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTOrder getMyOrder(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetCarByBrandNameEn", action = "http://UserOperationService.maichetong.chehui/GetCarByBrandNameEn")
    @RequestWrapper(localName = "GetCarByBrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByBrandNameEn")
    @ResponseWrapper(localName = "GetCarByBrandNameEnResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetCarByBrandNameEnResponse")
    @WebResult(name = "GetCarByBrandNameEnResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTSeries getCarByBrandNameEn(
        @WebParam(name = "BrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandNameEn,
        @WebParam(name = "SeriesId", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesId
    );

    @WebMethod(operationName = "GetBrandByid", action = "http://UserOperationService.maichetong.chehui/GetBrandByid")
    @RequestWrapper(localName = "GetBrandByid", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandByid")
    @ResponseWrapper(localName = "GetBrandByidResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetBrandByidResponse")
    @WebResult(name = "GetBrandByidResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBrand getBrandByid(
        @WebParam(name = "branid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String branid
    );

    @WebMethod(operationName = "GetGuidepriceByseriesId", action = "http://UserOperationService.maichetong.chehui/GetGuidepriceByseriesId")
    @RequestWrapper(localName = "GetGuidepriceByseriesId", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetGuidepriceByseriesId")
    @ResponseWrapper(localName = "GetGuidepriceByseriesIdResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetGuidepriceByseriesIdResponse")
    @WebResult(name = "GetGuidepriceByseriesIdResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTCar getGuidepriceByseriesId(
        @WebParam(name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetOrderByCarID", action = "http://UserOperationService.maichetong.chehui/GetOrderByCarID")
    @RequestWrapper(localName = "GetOrderByCarID", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetOrderByCarID")
    @ResponseWrapper(localName = "GetOrderByCarIDResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetOrderByCarIDResponse")
    @WebResult(name = "GetOrderByCarIDResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTOrder getOrderByCarID(
        @WebParam(name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetUserBusinessDDBH", action = "http://UserOperationService.maichetong.chehui/GetUserBusinessDDBH")
    @RequestWrapper(localName = "GetUserBusinessDDBH", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetUserBusinessDDBH")
    @ResponseWrapper(localName = "GetUserBusinessDDBHResponse", targetNamespace = "http://UserOperationService.maichetong.chehui/", className = "chehui.maichetong.useroperationservice.GetUserBusinessDDBHResponse")
    @WebResult(name = "GetUserBusinessDDBHResult", targetNamespace = "http://UserOperationService.maichetong.chehui/")
    public chehui.maichetong.useroperationservice.ResultOfListOfTBusiness getUserBusinessDDBH(
        @WebParam(name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid,
        @WebParam(name = "businessid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String businessid
    );
}
