package chehui.maichetong.useroperationservice;

import org.jinouts.jws.WebMethod;
import org.jinouts.jws.WebParam;
import org.jinouts.jws.WebResult;
import org.jinouts.jws.WebService;
import org.jinouts.jws.soap.SOAPBinding;
import org.jinouts.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-07-07T22:03:19.074+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://UserOperationService.maichetong.chehui/", name = "UserOperationServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserOperationServiceHttpPost {

    @WebMethod(operationName = "GetBrandABC")
    @WebResult(name = "ResultOfListOfTBrand", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBrand getBrandABC();

    @WebMethod(operationName = "OrderQueteBy")
    @WebResult(name = "ResultOfListOfTQuote", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTQuote orderQueteBy(
        @WebParam(partName = "fieldname", name = "fieldname", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String fieldname
    );

    @WebMethod(operationName = "GetSeriesByMakeName")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getSeriesByMakeName(
        @WebParam(partName = "brandName", name = "brandName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandName
    );

    @WebMethod(operationName = "GetallQueteByUser")
    @WebResult(name = "ResultOfListOfTQuote", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTQuote getallQueteByUser(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetCarColorByCarID")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getCarColorByCarID(
        @WebParam(partName = "carid", name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetQueteByCarID")
    @WebResult(name = "ResultOfListOfTQuote", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTQuote getQueteByCarID(
        @WebParam(partName = "carid", name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetSeriesByCar")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getSeriesByCar(
        @WebParam(partName = "brandName", name = "brandName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandName,
        @WebParam(partName = "makeName", name = "makeName", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String makeName
    );

    @WebMethod(operationName = "GetUserTel")
    @WebResult(name = "ResultOfListOfTUSER", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTUSER getUserTel(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetSeriesById")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getSeriesById(
        @WebParam(partName = "seriesid", name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetALLBrandName")
    @WebResult(name = "ResultOfListOfTBrand", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBrand getALLBrandName();

    @WebMethod(operationName = "GetSeriesByBrandid_Car")
    @WebResult(name = "ResultOfListOfTCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTCar getSeriesByBrandidCar(
        @WebParam(partName = "brandid", name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid,
        @WebParam(partName = "seriesid", name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetOrderCarName")
    @WebResult(name = "ResultOfListOfTCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTCar getOrderCarName(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetSeriesBybrandsCar")
    @WebResult(name = "ResultOfListOfTCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTCar getSeriesBybrandsCar(
        @WebParam(partName = "brandid", name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid,
        @WebParam(partName = "seriesid", name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid,
        @WebParam(partName = "seriescar", name = "seriescar", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriescar
    );

    @WebMethod(operationName = "GetBrandName")
    @WebResult(name = "ResultOfListOfTBrand", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBrand getBrandName(
        @WebParam(partName = "BrandABC", name = "BrandABC", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandABC
    );

    @WebMethod(operationName = "GetBrandNameByBrandNameEn")
    @WebResult(name = "ResultOfListOfTBrand", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBrand getBrandNameByBrandNameEn(
        @WebParam(partName = "BrandNameEn", name = "BrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandNameEn
    );

    @WebMethod(operationName = "GetMakeNames")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getMakeNames(
        @WebParam(partName = "makename", name = "makename", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String makename
    );

    @WebMethod(operationName = "GetCarByseriesId")
    @WebResult(name = "ResultOfListOfTCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTCar getCarByseriesId(
        @WebParam(partName = "seriesid", name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetSeriesName")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getSeriesName();

    @WebMethod(operationName = "GetMyOrderDetails")
    @WebResult(name = "ResultOfListOfTOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTOrder getMyOrderDetails(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid,
        @WebParam(partName = "carId", name = "carId", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carId
    );

    @WebMethod(operationName = "GetSeriesByBrandid")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getSeriesByBrandid(
        @WebParam(partName = "brandid", name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid
    );

    @WebMethod(operationName = "GetCarByBrandId")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getCarByBrandId(
        @WebParam(partName = "brandid", name = "brandid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandid
    );

    @WebMethod(operationName = "AddOrder")
    @WebResult(name = "ResultOfTOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfTOrder addOrder(
        @WebParam(partName = "userID", name = "userID", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userID,
        @WebParam(partName = "carID", name = "carID", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carID,
        @WebParam(partName = "cityname", name = "cityname", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String cityname,
        @WebParam(partName = "ExpectPrice", name = "ExpectPrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String expectPrice,
        @WebParam(partName = "InsurancePrice", name = "InsurancePrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String insurancePrice,
        @WebParam(partName = "LicensePrice", name = "LicensePrice", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String licensePrice,
        @WebParam(partName = "Description", name = "Description", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String description,
        @WebParam(partName = "carColor", name = "carColor", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carColor,
        @WebParam(partName = "CarPlan", name = "CarPlan", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carPlan,
        @WebParam(partName = "PayMode", name = "PayMode", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String payMode,
        @WebParam(partName = "CarAddress", name = "CarAddress", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carAddress,
        @WebParam(partName = "ZhuangHuang", name = "ZhuangHuang", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String zhuangHuang,
        @WebParam(partName = "kehuqw", name = "kehuqw", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String kehuqw
    );

    @WebMethod(operationName = "GetMyOrder")
    @WebResult(name = "ResultOfListOfTOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTOrder getMyOrder(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid
    );

    @WebMethod(operationName = "GetCarByBrandNameEn")
    @WebResult(name = "ResultOfListOfTSeries", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTSeries getCarByBrandNameEn(
        @WebParam(partName = "BrandNameEn", name = "BrandNameEn", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String brandNameEn,
        @WebParam(partName = "SeriesId", name = "SeriesId", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesId
    );

    @WebMethod(operationName = "GetBrandByid")
    @WebResult(name = "ResultOfListOfTBrand", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBrand getBrandByid(
        @WebParam(partName = "branid", name = "branid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String branid
    );

    @WebMethod(operationName = "GetGuidepriceByseriesId")
    @WebResult(name = "ResultOfListOfTCar", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTCar getGuidepriceByseriesId(
        @WebParam(partName = "seriesid", name = "seriesid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String seriesid
    );

    @WebMethod(operationName = "GetOrderByCarID")
    @WebResult(name = "ResultOfListOfTOrder", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTOrder getOrderByCarID(
        @WebParam(partName = "carid", name = "carid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String carid
    );

    @WebMethod(operationName = "GetUserBusinessDDBH")
    @WebResult(name = "ResultOfListOfTBusiness", targetNamespace = "http://UserOperationService.maichetong.chehui/", partName = "Body")
    public ResultOfListOfTBusiness getUserBusinessDDBH(
        @WebParam(partName = "userid", name = "userid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String userid,
        @WebParam(partName = "businessid", name = "businessid", targetNamespace = "http://UserOperationService.maichetong.chehui/")
        java.lang.String businessid
    );
}
